### ISSUE TITLE
The mode "-z" doesn‘t get seed.

### ISSUE THREAD

**Issue by wind-mask** [RLLD576/Slimefinder#1]
`case "-z":
                System.out.println("Insert x: ");
                int x = sc.nextInt();
                System.out.println("Insert y: ");
                int y = sc.nextInt();
                float[] point = finder.calcPos(x,y);
                System.out.println(point[0]);
                System.out.println(point[1]);
                System.out.println("The afk point has "+point[0]+" absolute chunks and "+point[1]+" partial chunks.");
                break;`

Adding `finder.seed = seed;` can solve it.

**Comment by RLLD576** [comment]
Done
